services:
  service:
    build: ./tetris
    environment:
      TETRIS_WS_SHARE_HTTP_PORT: true
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/4242 && exec 6<> /dev/tcp/localhost/4243"
  nginx:
    build: ./nginx
    depends_on:
      service:
        condition: service_healthy
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/80"
    ports:
      - "127.0.0.1:4242:80"
